export const ADD_QUOTE_BY_ID = 'ADD_QUOTE_BY_ID';
export const REMOVE_QUOTE_BY_ID = 'REMOVE_QUOTE_BY_ID';
export const LIKE_QUOTE_BY_ID = 'LIKE_QUOTE_BY_ID';
export const UNLIKE_QUOTE_BY_ID = 'UNLIKE_QUOTE_BY_ID';
export const UPDATE_THEME_COLOR = 'UPDATE_THEME_COLOR';
